/*
  Renders the two files of the generated gallery, .quasar/playwright-gallery/
  index.html and main.js. The HTML is the app's own template with the entry
  point marker replaced. The main file imports the app's CSS and hands the
  gallery runtime the app factory, the Quasar options, the boot files and the
  story files.

  The CSS import order and the boot normalization follow app-vite's
  templates/entry/client-entry.js. This module stays free of #q-app, vue,
  quasar and vite imports, so the test suite can run it under node.
*/

import path from 'node:path';
import { quote } from '../shared';
import { toPosixPath } from '../story-registry/render';

export const ENTRY_POINT_MARKER = '<!-- quasar:entry-point -->';

/** Where the generated files live, relative to the app. */
export const GALLERY_OUTPUT_DIRECTORY = '.quasar/playwright-gallery';
export const GALLERY_HTML_FILE_NAME = 'index.html';
export const GALLERY_MAIN_FILE_NAME = 'main.js';

const GALLERY_RUNTIME_MODULE =
  '@quasar/quasar-app-extension-testing-playwright/gallery';

const FILE_HEADER = `/* eslint-disable */
// Generated by @quasar/quasar-app-extension-testing-playwright on every
// quasar.config read of quasar dev, do not edit. It boots the app the way
// @quasar/app-vite's client entry does, with the gallery host as the root.`;

const ROOT_PUBLIC_PATH = '/';

// app-vite accepts a CDN url as the public path and leaves it as it is
const PUBLIC_PATH_URL_RE = /^http(s)?:\/\//i;

const CSS_ALIAS_PREFIX = '@/css';
const BOOT_ALIAS_PREFIX = '@/boot';
const AS_IS_PREFIX = '~';
const PARENT_DIRECTORY = '..';
const OPTION_INDENT = '  ';
const ENTRY_INDENT = '    ';

export interface CssAssetEntry {
  path: string;
  client?: boolean;
}

export type RawCssAsset = string | CssAssetEntry | null | undefined | false;

export interface BootAssetEntry {
  path: string;
  client?: boolean;
  server?: boolean;
}

export type RawBootAsset = string | BootAssetEntry | null | undefined | false;

/** What parseAssetProperty() returns. The css and the boot list share the shape. */
interface AssetEntry {
  path: string;
  client?: boolean;
}

type RawAsset = string | AssetEntry | null | undefined | false;

// A leading "~" means "use the path as-is", anything else lives under the alias.
function resolveAssetPath(assetPath: string, aliasPrefix: string) {
  if (assetPath.startsWith(AS_IS_PREFIX)) {
    return assetPath.slice(AS_IS_PREFIX.length);
  }

  return `${aliasPrefix}/${assetPath}`;
}

/**
 * Same rules as parseAssetProperty(aliasPrefix) and the client filter of
 * app-vite's entry template. app-vite deduplicates by path in the config file,
 * then the template drops the entries with "client: false". A path listed twice
 * keeps its first entry.
 */
function normalizeAssets(
  assets: ReadonlyArray<RawAsset>,
  aliasPrefix: string,
): string[] {
  const entries = new Map<string, AssetEntry>();

  for (const asset of assets) {
    if (!asset) {
      continue;
    }

    const entry: AssetEntry =
      typeof asset === 'string' ? { path: asset } : asset;

    if (typeof entry.path !== 'string') {
      continue;
    }

    const assetPath = resolveAssetPath(entry.path, aliasPrefix);
    if (!entries.has(assetPath)) {
      entries.set(assetPath, { ...entry, path: assetPath });
    }
  }

  return [...entries.values()]
    .filter((entry) => entry.client !== false)
    .map((entry) => entry.path);
}

/** Same rules as parseAssetProperty('@/boot') and the client filter of app-vite's entry template. */
export function normalizeBootAssets(
  boot: ReadonlyArray<RawBootAsset>,
): string[] {
  return normalizeAssets(boot, BOOT_ALIAS_PREFIX);
}

/** The path from the app directory, with posix separators on every platform. */
function toAppRelativePath(file: string, appDir: string) {
  const relative = path.posix.relative(toPosixPath(appDir), toPosixPath(file));

  if (
    relative === PARENT_DIRECTORY ||
    relative.startsWith(`${PARENT_DIRECTORY}/`)
  ) {
    throw new Error(
      `Cannot compute a web path for "${file}": it is outside the app directory "${appDir}".`,
    );
  }

  return relative;
}

/** "/abs/app/.quasar/dev-spa/app.js" with appDir "/abs/app" becomes "/.quasar/dev-spa/app.js". Throws when the file is outside appDir. */
export function toWebPath(file: string, appDir: string): string {
  return `/${toAppRelativePath(file, appDir)}`;
}

function renderModuleReference(modulePath: string) {
  const quoted = quote(modulePath);

  return `{ path: ${quoted}, load: () => import(${quoted}) }`;
}

/** An option value that spans lines, kept on one line when it has no entries. */
function renderBlock(entries: readonly string[], open: string, close: string) {
  if (entries.length === 0) {
    return `${open}${close}`;
  }

  const lines = entries.map((entry) => `${ENTRY_INDENT}${entry},`);

  return `${open}\n${lines.join('\n')}\n${OPTION_INDENT}${close}`;
}

/**
 * Same rules as formatPublicPath() of @quasar/app-vite. The index script reads the
 * raw config value, which app-vite has not normalized yet.
 */
export function normalizePublicPath(value: string | undefined): string {
  if (!value) {
    return ROOT_PUBLIC_PATH;
  }

  const withTrailingSlash = value.endsWith(ROOT_PUBLIC_PATH)
    ? value
    : `${value}${ROOT_PUBLIC_PATH}`;

  if (PUBLIC_PATH_URL_RE.test(withTrailingSlash)) {
    return withTrailingSlash;
  }

  if (withTrailingSlash.startsWith(ROOT_PUBLIC_PATH)) {
    return withTrailingSlash;
  }

  return `${ROOT_PUBLIC_PATH}${withTrailingSlash}`;
}

// Vite's dev html transform joins config.base onto every root-absolute src, so
// the tag has no public path. app-vite writes its own entry tag the same way.
const ENTRY_POINT_REPLACEMENT = `<div id="q-app"></div>\n<script type="module" src="/${GALLERY_OUTPUT_DIRECTORY}/${GALLERY_MAIN_FILE_NAME}"></script>`;

export interface GalleryHtmlInput {
  template: string;
  templatePath: string;
}

export function renderGalleryHtml(input: GalleryHtmlInput): string {
  const { template, templatePath } = input;

  if (!template.includes(ENTRY_POINT_MARKER)) {
    throw new Error(
      `${templatePath} has no "${ENTRY_POINT_MARKER}" marker. The gallery needs it where Quasar's own entry renders the app.`,
    );
  }

  return template.replace(ENTRY_POINT_MARKER, ENTRY_POINT_REPLACEMENT);
}

export interface GalleryMainInput {
  extras: ReadonlyArray<string | null | undefined | false>;
  animations: ReadonlyArray<string | null | undefined | false>;
  css: ReadonlyArray<RawCssAsset>;
  cssAddon: boolean;
  quasarSrcExt: 'sass' | 'css';
  boot: ReadonlyArray<RawBootAsset>;
  appFactoryWebPath: string;
  quasarUserOptionsWebPath: string;
  /** Absolute story files, from listStoryFiles(). */
  storyFiles: readonly string[];
  appDir: string;
  publicPath: string;
  vueRouterMode: 'hash' | 'history';
}

function renderCssImports(input: GalleryMainInput): string[] {
  const lines: string[] = [];

  for (const asset of input.extras) {
    if (asset) {
      lines.push(`import ${quote(`@quasar/extras/${asset}/${asset}.css`)};`);
    }
  }

  for (const asset of input.animations) {
    if (asset) {
      lines.push(`import ${quote(`@quasar/extras/animate/${asset}.css`)};`);
    }
  }

  lines.push(`import ${quote(`quasar/dist/quasar.${input.quasarSrcExt}`)};`);

  if (input.cssAddon) {
    lines.push(`import ${quote('quasar/src/css/flex-addon.sass')};`);
  }

  for (const assetPath of normalizeAssets(input.css, CSS_ALIAS_PREFIX)) {
    lines.push(`import ${quote(assetPath)};`);
  }

  return lines;
}

function renderStoryEntries(input: GalleryMainInput): string[] {
  return input.storyFiles.map((file) => {
    const storyPath = toAppRelativePath(file, input.appDir);

    // The key is the app-relative path the registry uses. The value imports the
    // root-absolute one, which Vite resolves against the app root.
    return `${quote(storyPath)}: () => import(${quote(`/${storyPath}`)})`;
  });
}

export function renderGalleryMain(input: GalleryMainInput): string {
  const bootEntries = normalizeBootAssets(input.boot).map(
    renderModuleReference,
  );
  const storyEntries = renderStoryEntries(input);

  const options = [
    `appFactory: ${renderModuleReference(input.appFactoryWebPath)},`,
    `quasarUserOptions: ${renderModuleReference(input.quasarUserOptionsWebPath)},`,
    `bootFiles: ${renderBlock(bootEntries, '[', ']')},`,
    `stories: ${renderBlock(storyEntries, '{', '}')},`,
    `publicPath: ${quote(input.publicPath)},`,
    `vueRouterMode: ${quote(input.vueRouterMode)},`,
  ];

  return [
    FILE_HEADER,
    '',
    ...renderCssImports(input),
    `import { createQuasarGallery } from ${quote(GALLERY_RUNTIME_MODULE)};`,
    '',
    'createQuasarGallery({',
    ...options.map((option) => `${OPTION_INDENT}${option}`),
    '});',
    '',
  ].join('\n');
}
