import { expect, test } from 'vitest';
import {
  ENTRY_POINT_MARKER,
  normalizeBootAssets,
  normalizePublicPath,
  renderGalleryHtml,
  renderGalleryMain,
  toWebPath,
  type BootAssetEntry,
  type CssAssetEntry,
  type GalleryMainInput,
} from './render';

const MAIN_HEADER = [
  '/* eslint-disable */',
  '// Generated by @quasar/quasar-app-extension-testing-playwright on every',
  '// quasar.config read of quasar dev, do not edit. It boots the app the way',
  "// @quasar/app-vite's client entry does, with the gallery host as the root.",
  '',
];

const MAIN_INPUT: GalleryMainInput = {
  extras: [],
  animations: [],
  css: [],
  cssAddon: false,
  quasarSrcExt: 'css',
  boot: [],
  appFactoryWebPath: '/.quasar/dev-spa/app.js',
  quasarUserOptionsWebPath: '/.quasar/dev-spa/quasar-user-options.js',
  storyFiles: [],
  appDir: '/app',
  publicPath: '/',
  vueRouterMode: 'history',
};

test('normalizeBootAssets resolves a string against the boot alias', () => {
  expect(normalizeBootAssets(['i18n', 'axios'])).toStrictEqual([
    '@/boot/i18n',
    '@/boot/axios',
  ]);
});

test('normalizeBootAssets keeps a tilde string as it is', () => {
  expect(normalizeBootAssets(['~some-package/boot/setup'])).toStrictEqual([
    'some-package/boot/setup',
  ]);
});

test('normalizeBootAssets resolves the path of an object entry', () => {
  expect(
    normalizeBootAssets([
      { path: 'i18n' },
      { path: '~some-package/boot/setup' },
      { path: 'ssr-only', server: true },
    ]),
  ).toStrictEqual([
    '@/boot/i18n',
    'some-package/boot/setup',
    '@/boot/ssr-only',
  ]);
});

test('normalizeBootAssets drops the entries the client does not run', () => {
  // Nothing checks the config values at runtime, so an entry can hold any path value.
  const withNumberPath = { path: 42 } as unknown as BootAssetEntry;

  expect(
    normalizeBootAssets([
      { path: 'server-only', client: false },
      withNumberPath,
    ]),
  ).toStrictEqual([]);
});

test('normalizeBootAssets deduplicates before it drops the server entries', () => {
  expect(
    normalizeBootAssets([{ path: 'i18n', client: false }, 'i18n']),
  ).toStrictEqual([]);
});

test('normalizeBootAssets drops duplicates and keeps the first one', () => {
  expect(
    normalizeBootAssets(['i18n', { path: 'i18n' }, 'axios', 'i18n']),
  ).toStrictEqual(['@/boot/i18n', '@/boot/axios']);
});

test('normalizeBootAssets drops falsy entries', () => {
  expect(
    normalizeBootAssets([null, undefined, false, '', 'i18n']),
  ).toStrictEqual(['@/boot/i18n']);
});

test('toWebPath makes a file inside the app root absolute', () => {
  expect(toWebPath('/abs/app/.quasar/dev-spa/app.js', '/abs/app')).toBe(
    '/.quasar/dev-spa/app.js',
  );
});

test('toWebPath converts windows separators', () => {
  expect(
    toWebPath('C:\\abs\\app\\.quasar\\dev-pwa\\app.js', 'C:\\abs\\app'),
  ).toBe('/.quasar/dev-pwa/app.js');
});

test('toWebPath rejects a file outside the app directory', () => {
  expect(() => toWebPath('/abs/other/app.js', '/abs/app')).toThrow(
    new Error(
      'Cannot compute a web path for "/abs/other/app.js": it is outside the app directory "/abs/app".',
    ),
  );
});

test('normalizePublicPath falls back to the root for an empty value', () => {
  expect(normalizePublicPath(undefined)).toBe('/');
  expect(normalizePublicPath('')).toBe('/');
  expect(normalizePublicPath('/')).toBe('/');
});

test('normalizePublicPath adds the missing slashes', () => {
  expect(normalizePublicPath('my-app')).toBe('/my-app/');
  expect(normalizePublicPath('/my-app')).toBe('/my-app/');
  expect(normalizePublicPath('my-app/')).toBe('/my-app/');
  expect(normalizePublicPath('/my-app/')).toBe('/my-app/');
});

test('normalizePublicPath keeps an absolute url as its own base', () => {
  expect(normalizePublicPath('https://cdn.example.com/app')).toBe(
    'https://cdn.example.com/app/',
  );
});

test('renderGalleryHtml replaces the first entry point marker', () => {
  const html = renderGalleryHtml({
    template: `<body>\n  ${ENTRY_POINT_MARKER}\n  ${ENTRY_POINT_MARKER}\n</body>\n`,
    templatePath: '/app/index.html',
  });

  expect(html).toBe(
    [
      '<body>',
      '  <div id="q-app"></div>',
      '<script type="module" src="/.quasar/playwright-gallery/main.js"></script>',
      `  ${ENTRY_POINT_MARKER}`,
      '</body>',
      '',
    ].join('\n'),
  );
});

test('renderGalleryHtml keeps the html variables verbatim', () => {
  const html = renderGalleryHtml({
    template: `<title><%= productName %></title>\n${ENTRY_POINT_MARKER}\n`,
    templatePath: '/app/index.html',
  });

  expect(html).toMatch(/<title><%= productName %><\/title>/);
});

test('renderGalleryHtml rejects a template without the marker', () => {
  expect(() =>
    renderGalleryHtml({
      template: '<body></body>\n',
      templatePath: '/app/index.html',
    }),
  ).toThrow(
    new Error(
      '/app/index.html has no "<!-- quasar:entry-point -->" marker. The gallery needs it where Quasar\'s own entry renders the app.',
    ),
  );
});

test('renderGalleryMain renders the css imports in the order of the client entry', () => {
  const main = renderGalleryMain({
    ...MAIN_INPUT,
    extras: ['roboto-font', undefined, 'material-icons'],
    animations: ['fadeIn'],
    css: [
      'app.scss',
      { path: 'print.css', client: false },
      '~normalize.css/normalize.css',
      false,
    ],
    cssAddon: true,
    quasarSrcExt: 'sass',
  });

  expect(main).toBe(
    [
      ...MAIN_HEADER,
      "import '@quasar/extras/roboto-font/roboto-font.css';",
      "import '@quasar/extras/material-icons/material-icons.css';",
      "import '@quasar/extras/animate/fadeIn.css';",
      "import 'quasar/dist/quasar.sass';",
      "import 'quasar/src/css/flex-addon.sass';",
      "import '@/css/app.scss';",
      "import 'normalize.css/normalize.css';",
      "import { createQuasarGallery } from '@quasar/quasar-app-extension-testing-playwright/gallery';",
      '',
      'createQuasarGallery({',
      "  appFactory: { path: '/.quasar/dev-spa/app.js', load: () => import('/.quasar/dev-spa/app.js') },",
      "  quasarUserOptions: { path: '/.quasar/dev-spa/quasar-user-options.js', load: () => import('/.quasar/dev-spa/quasar-user-options.js') },",
      '  bootFiles: [],',
      '  stories: {},',
      "  publicPath: '/',",
      "  vueRouterMode: 'history',",
      '});',
      '',
    ].join('\n'),
  );
});

test('renderGalleryMain uses the plain css build without a sass variables file', () => {
  const main = renderGalleryMain(MAIN_INPUT);

  expect(main).toBe(
    [
      ...MAIN_HEADER,
      "import 'quasar/dist/quasar.css';",
      "import { createQuasarGallery } from '@quasar/quasar-app-extension-testing-playwright/gallery';",
      '',
      'createQuasarGallery({',
      "  appFactory: { path: '/.quasar/dev-spa/app.js', load: () => import('/.quasar/dev-spa/app.js') },",
      "  quasarUserOptions: { path: '/.quasar/dev-spa/quasar-user-options.js', load: () => import('/.quasar/dev-spa/quasar-user-options.js') },",
      '  bootFiles: [],',
      '  stories: {},',
      "  publicPath: '/',",
      "  vueRouterMode: 'history',",
      '});',
      '',
    ].join('\n'),
  );
});

test('renderGalleryMain renders the boot files and the stories', () => {
  const main = renderGalleryMain({
    ...MAIN_INPUT,
    boot: ['i18n'],
    storyFiles: ['/app/src/components/Button.story.tsx'],
    publicPath: '/app/',
    vueRouterMode: 'hash',
  });

  expect(main).toBe(
    [
      ...MAIN_HEADER,
      "import 'quasar/dist/quasar.css';",
      "import { createQuasarGallery } from '@quasar/quasar-app-extension-testing-playwright/gallery';",
      '',
      'createQuasarGallery({',
      "  appFactory: { path: '/.quasar/dev-spa/app.js', load: () => import('/.quasar/dev-spa/app.js') },",
      "  quasarUserOptions: { path: '/.quasar/dev-spa/quasar-user-options.js', load: () => import('/.quasar/dev-spa/quasar-user-options.js') },",
      '  bootFiles: [',
      "    { path: '@/boot/i18n', load: () => import('@/boot/i18n') },",
      '  ],',
      '  stories: {',
      "    'src/components/Button.story.tsx': () => import('/src/components/Button.story.tsx'),",
      '  },',
      "  publicPath: '/app/',",
      "  vueRouterMode: 'hash',",
      '});',
      '',
    ].join('\n'),
  );
});

test('renderGalleryMain deduplicates css before it drops the server entries', () => {
  const main = renderGalleryMain({
    ...MAIN_INPUT,
    css: [{ path: 'app.css', client: false }, 'app.css'],
  });

  expect(main).not.toMatch(/app\.css/);
});

test('renderGalleryMain imports a duplicated css entry once', () => {
  const main = renderGalleryMain({
    ...MAIN_INPUT,
    css: ['app.css', { path: 'app.css' }],
  });

  expect(main.match(/^import '@\/css\/app\.css';$/gm)?.length).toBe(1);
});

test('renderGalleryMain drops a css entry whose path is not a string', () => {
  // Nothing checks the config values at runtime, so an entry can hold any path value.
  const withNumberPath = { path: 42 } as unknown as CssAssetEntry;

  const main = renderGalleryMain({ ...MAIN_INPUT, css: [withNumberPath] });

  expect(main).not.toMatch(/^import .*42.*;$/m);
});

test('renderGalleryMain converts windows story paths to posix', () => {
  const main = renderGalleryMain({
    ...MAIN_INPUT,
    appDir: 'C:\\app',
    storyFiles: ['C:\\app\\src\\components\\Button.story.tsx'],
  });

  expect(main).toMatch(
    /^ {4}'src\/components\/Button\.story\.tsx': \(\) => import\('\/src\/components\/Button\.story\.tsx'\),$/m,
  );
});

test('renderGalleryMain rejects a story file outside the app directory', () => {
  expect(() =>
    renderGalleryMain({
      ...MAIN_INPUT,
      storyFiles: ['/elsewhere/Button.story.tsx'],
    }),
  ).toThrow(
    new Error(
      'Cannot compute a web path for "/elsewhere/Button.story.tsx": it is outside the app directory "/app".',
    ),
  );
});

test('renderGalleryMain escapes quotes and backslashes in generated strings', () => {
  const main = renderGalleryMain({
    ...MAIN_INPUT,
    css: ['~it\\s/style.css'],
    storyFiles: ["/app/src/o'brien/Button.story.tsx"],
  });

  expect(main).toMatch(/^import 'it\\\\s\/style\.css';$/m);
  expect(main).toMatch(
    /^ {4}'src\/o\\'brien\/Button\.story\.tsx': \(\) => import\('\/src\/o\\'brien\/Button\.story\.tsx'\),$/m,
  );
});
