/*
  Renders .quasar/playwright.d.ts. It lists every story file of the app, so
  mount() completes the story ids and type-checks their props, and it declares
  the global the gallery page sets and the env key the AE defines. Playwright
  declares an empty "Stories" interface in @playwright/test. Every key of it is
  a known story id.
*/

import { existsSync, readdirSync } from 'node:fs';
import path from 'node:path';
import {
  AE_SWITCH_VARIABLE,
  GALLERY_FLAG,
  STORY_FILE_RE,
  quote,
  toStoryId as toIdFromAppPath,
} from '../shared';

export { STORY_FILE_RE };

const IGNORED_DIRECTORY = 'node_modules';
const SFC_EXTENSION = '.vue';

const FILE_HEADER = `/* eslint-disable */
// Generated by @quasar/quasar-app-extension-testing-playwright on every
// quasar prepare, dev and build, do not edit. It lists every *.story.* file of
// the app so mount() autocompletes the story ids and type-checks their props,
// and declares the global the gallery page sets and the env key the AE defines.

// prettier-ignore
type StoriesOf<Prefix extends string, Mod> = {
  [K in keyof Mod & string as K extends 'default' ? Prefix : \`\${Prefix}/\${K}\`]: Mod[K];
};
`;

const GALLERY_FLAG_DECLARATION = `declare global {
  /** Set by the Playwright gallery page before any boot file runs. Absent in the app and under SSR. */
  var ${GALLERY_FLAG}: true | undefined;
}
`;

// app-vite writes its own ImportMetaEnv interface into .quasar/quasar.d.ts, and
// skips every import.meta.env.QUASAR_ key there. So the key the index script
// defines is declared here.
const AE_SWITCH_DECLARATION = `declare global {
  interface ImportMetaEnv {
    /** True while the app runs under Playwright. The AE defines it on every dev, build and prepare. */
    readonly ${AE_SWITCH_VARIABLE}: boolean;
  }
}
`;

function collectStoryFiles(dir: string): string[] {
  const files: string[] = [];

  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const entryPath = path.join(dir, entry.name);

    if (entry.isDirectory()) {
      if (entry.name !== IGNORED_DIRECTORY) {
        files.push(...collectStoryFiles(entryPath));
      }
      continue;
    }

    if (STORY_FILE_RE.test(entry.name)) {
      files.push(entryPath);
    }
  }

  return files;
}

/** Absolute paths of every story file under the roots, sorted, recursive. */
export function listStoryFiles(roots: readonly string[]): string[] {
  const files: string[] = [];

  for (const root of roots) {
    // A root is optional. The demo suite is only scaffolded on request.
    if (existsSync(root)) {
      files.push(...collectStoryFiles(root));
    }
  }

  // The two roots the index script passes cannot nest. The dedupe only guards
  // a later change to them.
  return [...new Set(files)].sort();
}

export interface StoryTypesOptions {
  appDir: string;
  roots: string[];
  outFile: string;
}

/** The same path with forward slashes, so a Windows path reads like a module specifier. */
export function toPosixPath(filePath: string) {
  return filePath.replaceAll('\\', '/');
}

/**
 * The id is the path from the app root with a leading src/ dropped, matching
 * the rule the gallery applies to its glob keys.
 * "/app/src/components/Button.story.tsx" becomes "components/Button".
 * "/app/test/playwright/demo/QuasarSelect.story.tsx" keeps its full path.
 */
export function toStoryId(file: string, appDir: string) {
  return toIdFromAppPath(toPosixPath(path.relative(appDir, file)));
}

// TypeScript resolves "./X.story" by appending ".ts" or ".tsx". A .vue module
// must be named with its extension.
function toModuleSpecifier(file: string, outDir: string) {
  const relative = toPosixPath(path.relative(outDir, file));
  const specifier = relative.startsWith('.') ? relative : `./${relative}`;

  if (specifier.endsWith(SFC_EXTENSION)) {
    return specifier;
  }

  return specifier.slice(0, specifier.lastIndexOf('.'));
}

/** The content of the registry for the given story files. */
export function renderStoryTypes(
  files: string[],
  options: StoryTypesOptions,
): string {
  const outDir = path.dirname(options.outFile);
  const entries = files.map((file) => {
    const storyId = toStoryId(file, options.appDir);
    const specifier = toModuleSpecifier(file, outDir);

    return `    StoriesOf<${quote(storyId)}, typeof import(${quote(specifier)})>`;
  });

  const declaration =
    entries.length === 0
      ? '  interface Stories {}'
      : `  interface Stories extends\n${entries.join(',\n')} {}`;

  return `${FILE_HEADER}
// prettier-ignore
declare module '@playwright/test' {
${declaration}
}

${GALLERY_FLAG_DECLARATION}
${AE_SWITCH_DECLARATION}
export {};
`;
}
