import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { expect, onTestFinished, test } from 'vitest';
import { storyFileId } from '../gallery/resolve-story';
import { listStoryFiles, renderStoryTypes, toStoryId } from './render';

// The render tests pass their story files in, so roots is never read here.
const OPTIONS = {
  appDir: '/app',
  roots: ['/app/src', '/app/test/playwright'],
  outFile: '/app/.quasar/playwright.d.ts',
};

const HEADER = `/* eslint-disable */
// Generated by @quasar/quasar-app-extension-testing-playwright on every
// quasar prepare, dev and build, do not edit. It lists every *.story.* file of
// the app so mount() autocompletes the story ids and type-checks their props,
// and declares the global the gallery page sets and the env key the AE defines.

// prettier-ignore
type StoriesOf<Prefix extends string, Mod> = {
  [K in keyof Mod & string as K extends 'default' ? Prefix : \`\${Prefix}/\${K}\`]: Mod[K];
};
`;

test('renders one entry per story file, dropping the leading src/', () => {
  const content = renderStoryTypes(
    [
      '/app/src/components/QuasarButton.story.tsx',
      '/app/test/playwright/demo/QuasarDialog.default.story.vue',
      '/app/test/playwright/demo/QuasarSelect.story.ts',
    ],
    OPTIONS,
  );

  expect(content).toBe(`${HEADER}
// prettier-ignore
declare module '@playwright/test' {
  interface Stories extends
    StoriesOf<'components/QuasarButton', typeof import('../src/components/QuasarButton.story')>,
    StoriesOf<'test/playwright/demo/QuasarDialog.default', typeof import('../test/playwright/demo/QuasarDialog.default.story.vue')>,
    StoriesOf<'test/playwright/demo/QuasarSelect', typeof import('../test/playwright/demo/QuasarSelect.story')> {}
}

declare global {
  /** Set by the Playwright gallery page before any boot file runs. Absent in the app and under SSR. */
  var __QUASAR_PLAYWRIGHT_GALLERY__: true | undefined;
}

declare global {
  interface ImportMetaEnv {
    /** True while the app runs under Playwright. The AE defines it on every dev, build and prepare. */
    readonly QUASAR_TESTING_PLAYWRIGHT: boolean;
  }
}

export {};
`);
});

test('renders an empty interface without story files', () => {
  expect(renderStoryTypes([], OPTIONS)).toBe(`${HEADER}
// prettier-ignore
declare module '@playwright/test' {
  interface Stories {}
}

declare global {
  /** Set by the Playwright gallery page before any boot file runs. Absent in the app and under SSR. */
  var __QUASAR_PLAYWRIGHT_GALLERY__: true | undefined;
}

declare global {
  interface ImportMetaEnv {
    /** True while the app runs under Playwright. The AE defines it on every dev, build and prepare. */
    readonly QUASAR_TESTING_PLAYWRIGHT: boolean;
  }
}

export {};
`);
});

test('declares the AE switch on ImportMetaEnv as a required boolean', () => {
  const content = renderStoryTypes([], OPTIONS);

  expect(content).toContain('  interface ImportMetaEnv {');
  expect(content).toContain('    readonly QUASAR_TESTING_PLAYWRIGHT: boolean;');
});

test('lists story files recursively and skips node_modules', () => {
  const appDir = mkdtempSync(path.join(tmpdir(), 'story-registry-'));
  onTestFinished(() => rmSync(appDir, { recursive: true, force: true }));
  const srcDir = path.join(appDir, 'src');

  mkdirSync(path.join(srcDir, 'a/b'), { recursive: true });
  mkdirSync(path.join(srcDir, 'node_modules'));
  writeFileSync(path.join(srcDir, 'a/B.story.tsx'), '');
  writeFileSync(path.join(srcDir, 'a/b/C.story.vue'), '');
  writeFileSync(path.join(srcDir, 'a/not-a-story.ts'), '');
  writeFileSync(path.join(srcDir, 'node_modules/x.story.ts'), '');

  expect(listStoryFiles([srcDir])).toStrictEqual([
    path.join(srcDir, 'a/B.story.tsx'),
    path.join(srcDir, 'a/b/C.story.vue'),
  ]);
});

test('escapes an apostrophe in the story id and the specifier', () => {
  const content = renderStoryTypes(
    ["/app/src/components/Ben's Button.story.tsx"],
    OPTIONS,
  );

  expect(content).toContain(
    "StoriesOf<'components/Ben\\'s Button', typeof import('../src/components/Ben\\'s Button.story')>",
  );
});

test('gives a story the same id as the gallery does', () => {
  const cases = [
    {
      galleryKey: 'test/playwright/demo/X.story.tsx',
      registryFile: '/app/test/playwright/demo/X.story.tsx',
      id: 'test/playwright/demo/X',
    },
    {
      galleryKey: 'src/components/X.story.vue',
      registryFile: '/app/src/components/X.story.vue',
      id: 'components/X',
    },
    // Both sides read one rule, so every extension of it agrees
    ...['ts', 'tsx', 'js', 'jsx'].map((extension) => ({
      galleryKey: `src/components/X.story.${extension}`,
      registryFile: `/app/src/components/X.story.${extension}`,
      id: 'components/X',
    })),
    // "src" only comes off the front
    {
      galleryKey: 'test/src/X.story.ts',
      registryFile: '/app/test/src/X.story.ts',
      id: 'test/src/X',
    },
  ];

  for (const { galleryKey, registryFile, id } of cases) {
    expect(storyFileId(galleryKey)).toBe(id);
    expect(toStoryId(registryFile, '/app')).toBe(id);
  }
});

test('unions the roots, sorts once and skips a missing root', () => {
  const appDir = mkdtempSync(path.join(tmpdir(), 'story-registry-'));
  onTestFinished(() => rmSync(appDir, { recursive: true, force: true }));
  const srcDir = path.join(appDir, 'src');
  const demoDir = path.join(appDir, 'test/playwright/demo');

  mkdirSync(srcDir, { recursive: true });
  mkdirSync(demoDir, { recursive: true });
  writeFileSync(path.join(srcDir, 'Button.story.tsx'), '');
  writeFileSync(path.join(demoDir, 'QuasarSelect.story.tsx'), '');

  expect(
    listStoryFiles([
      srcDir,
      path.join(appDir, 'test/playwright'),
      path.join(appDir, 'missing'),
    ]),
  ).toStrictEqual([
    path.join(srcDir, 'Button.story.tsx'),
    path.join(demoDir, 'QuasarSelect.story.tsx'),
  ]);
});
